[package]
name = "rspirv"
version = "0.1.0"
authors = ["Lei Zhang <antiagainst@gmail.com>"]

build = "build.rs"

description = "Rust library APIs for SPIR-V module manipulation"
documentation = "https://docs.rs/rspirv"
repository = "https://github.com/google/rspirv"
readme = "../README.md"
license = "Apache-2.0"
keywords = ["spirv", "vulkan", "opengl", "opencl"]

[lib]
path = "lib.rs"

[dependencies]
bitflags = "0.6"
num = { git = "https://github.com/rust-num/num" }
num-macros = { git = "https://github.com/rust-num/num" }

[build-dependencies]
regex = "0.1"
serde = "0.8"
serde_json = "0.8"

[dev-dependencies]
assert_matches = "1.0"
