language: rust

sudo: false
os:
  - linux
  - osx
rust:
  - stable
  - nightly

matrix:
  fast_finish: true

branches:
  only:
    - master

script:
  - cd spirv/
  - cargo build --verbose
  - cd ../rspirv/
  - cargo build --verbose
  - cargo build --features regen
  - cargo test --verbose
  - cd ../dis/
  - cargo build

notifications:
  email:
    recipients:
      - antiagainst@gmail.com
    on_success: change
    on_failure: always
