language: rust

sudo: false
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
    - os: windows
      rust: stable

branches:
  except:
    - staging.tmp

before_script:
  - git submodule update --init
  - rustup component add rustfmt

script:
  - cargo check --verbose
  - git diff --exit-code
  - cargo test --verbose
